shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/vite-plugin-bundle-visual-viewer
  - packages/vite-plugin-bundle-visual
  - packages/vite-plugin-css-props
  - packages/vite-plugin-css-props/test-fixtures/*
