import type { NormalizedCssConfig } from '../types'

function literal(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, '\\\'')}'`
}

function buildInterface(
  name: string,
  tokens: readonly string[],
  valueFor: (token: string) => string,
): string {
  if (tokens.length === 0)
    return `  interface ${name} {}`
  const body = tokens
    .map(token => `    readonly ${literal(token)}: ${literal(valueFor(token))}`)
    .join('\n')
  return `  interface ${name} {\n${body}\n  }`
}

export function generateDts(config: NormalizedCssConfig): string {
  const colorVars = buildInterface('ColorVars', config.colors.tokens, t => config.varExpr(t))
  const colorLight = buildInterface('ColorLightValues', config.colors.tokens, t => config.colors.light[t])
  const colorDark = buildInterface('ColorDarkValues', config.colors.tokens, t => config.colors.dark[t])
  const propVars = buildInterface('PropVars', config.props.tokens, t => config.varExpr(t))
  const propValues = buildInterface('PropValues', config.props.tokens, t => config.props.values[t])

  return `// AUTO-GENERATED by vite-plugin-css-props — DO NOT EDIT

declare module 'virtual:css-props' {
  export type ThemeName = 'light' | 'dark'

${colorVars}

${colorLight}

${colorDark}

${propVars}

${propValues}

  type ColorValuesByName = {
    readonly light: ColorLightValues
    readonly dark: ColorDarkValues
  }

  export type ColorToken = keyof ColorVars
  export type PropToken = keyof PropVars

  export function colorVar<T extends ColorToken>(token: T): ColorVars[T]

  export function colorVal<T extends ColorToken>(token: T): ColorLightValues[T]
  export function colorVal<T extends ColorToken, N extends ThemeName>(
    token: T,
    theme: N,
  ): ColorValuesByName[N][T]

  export function colorKeys(): readonly ColorToken[]

  export function propVar<T extends PropToken>(token: T): PropVars[T]
  export function propVal<T extends PropToken>(token: T): PropValues[T]
  export function propKeys(): readonly PropToken[]

  export function alpha(input: string, ratio: number): string
  export function lighten(input: string, ratio: number): string
  export function darken(input: string, ratio: number): string
  export function mix(colorA: string, colorB: string, weight?: number): string
}
`
}
