import type { NormalizedColors, NormalizedCssConfig, NormalizedProps } from '../types'

function buildMapLiteral(entries: Readonly<Record<string, string>>): string {
  const lines = Object.entries(entries)
    .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)}`)
    .join(',\n')
  return `{\n${lines}\n}`
}

function buildColorVars(colors: NormalizedColors, varExpr: (token: string) => string): Record<string, string> {
  const vars: Record<string, string> = {}
  for (const token of colors.tokens)
    vars[token] = varExpr(token)
  return vars
}

function buildPropVars(props: NormalizedProps, varExpr: (token: string) => string): Record<string, string> {
  const vars: Record<string, string> = {}
  for (const token of props.tokens)
    vars[token] = varExpr(token)
  return vars
}

export function generateJs(config: NormalizedCssConfig): string {
  const colorVars = buildColorVars(config.colors, config.varExpr)
  const propVars = buildPropVars(config.props, config.varExpr)
  const colorKeysLiteral = JSON.stringify(config.colors.tokens)
  const propKeysLiteral = JSON.stringify(config.props.tokens)

  return `// AUTO-GENERATED by vite-plugin-css-props
import { createColorOps } from 'vite-plugin-css-props/runtime'

const COLOR_VARS = ${buildMapLiteral(colorVars)}
const COLOR_LIGHT = ${buildMapLiteral(config.colors.light)}
const COLOR_DARK = ${buildMapLiteral(config.colors.dark)}
const COLOR_KEYS = Object.freeze(${colorKeysLiteral})

const PROP_VARS = ${buildMapLiteral(propVars)}
const PROP_VALUES = ${buildMapLiteral(config.props.values)}
const PROP_KEYS = Object.freeze(${propKeysLiteral})

const __ops = createColorOps()
export const alpha = __ops.alpha
export const lighten = __ops.lighten
export const darken = __ops.darken
export const mix = __ops.mix

export function colorVar(token) {
  return COLOR_VARS[token]
}

export function colorVal(token, theme) {
  return theme === 'dark' ? COLOR_DARK[token] : COLOR_LIGHT[token]
}

export function colorKeys() {
  return COLOR_KEYS
}

export function propVar(token) {
  return PROP_VARS[token]
}

export function propVal(token) {
  return PROP_VALUES[token]
}

export function propKeys() {
  return PROP_KEYS
}
`
}
